name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: enrico-gianoglio-deployment #Must be unique in Heroku
          heroku_email: enry8giano@gmail.com
# name: Hello World!

# on:
#   push:
#     branches:
#       - master

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Say hello
#         run: |
#           echo "Hello World!"
#       - name: Date is
#         run: |
#           date
#       - name: Directory Content
#         run: |
#           ls -l
