name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint        
# name: Hello World!

# on:
#   push:
#     branches:
#       - master

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-18.04
#     steps:
#       - name: Say hello
#         run: |
#           echo "Hello World!"
#       - name: Date is
#         run: |
#           date
#       - name: Directory Content
#         run: |
#           ls -l
